name: Feature Request
description: Suggest a new feature for zen
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: I would like zen to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: Other ways this could work...

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: How would you use this feature?
      placeholder: |
        ```bash
        zen example-command
        ```

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information about this feature
      placeholder: Related tools, mockups, etc.