name: Update Homebrew Tap

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to update Homebrew formula to'
        required: true
        default: 'v0.1.1'

jobs:
  update-tap:
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew tap
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: zen
          homebrew-tap: MaazSiddiqi/homebrew-tap
          download-url: https://github.com/MaazSiddiqi/zen/archive/${{ github.event.inputs.tag || github.ref_name }}.tar.gz
          commit-message: "Update zen to ${{ github.event.inputs.tag || github.ref_name }}"
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}